### ISSUE TITLE
Exception HRESULT: 0x80040201

### ISSUE THREAD

**Issue by ilwsm** [loxia01/PSInternetConnectionSharing#2]
![image](https://user-images.githubusercontent.com/2471892/119336646-91abbe00-bc96-11eb-95b8-e7af48ada067.png)

Cant make ics.
What the errors?

**Comment by loxia01** [comment]
Hello, could you test if v1.01 works for you?
https://github.com/loxia01/PSInternetConnectionSharing/releases/download/v1.01/PSInternetConnectionSharing.psm1

Replace your psm1 file with this.

**Comment by loxia01** [comment]
It seems to be a known ICS error:
https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/e38d467e-5d0b-4338-8627-b960f3f9a847/systemruntimeinteropservicescomexception-0x80040201-when-setting-internet-connection-sharing?forum=windowsgeneraldevelopmentissues
